trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'test'
  dockerfilePath: 'spring-boot-application/Dockerfile'
  azureContainerRegistry: 'cloudorbit.azurecr.io'
  azureResourceGroup: 'cloudorbit-resource-grp'
  kubernetesCluster: 'cloudobrit-cluster'
  kubernetesNamespace: 'dev'
  tag: '$(Build.BuildId)'

- stage: Build
  displayName: Build and push docker image to acr
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(azureContainerRegistry)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(tag)

# deploying containers on aks pulled from azure container registry
jobs:
- deployment:
  displayName: Deploy to AKS
  pool:
    vmImage: $(vmImage)
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
        - task: KubernetesManifest@0
          displayName: Deploy
          inputs:
            action: deploy
            namespace: $(kubernetesNamespace)
            manifests: aks-deployments/app.yaml
            containers: |
              $(azureContainerRegistry)/$(imageName):$COMMIT_SHA
              $(azureContainerRegistry)/$(imageName):latest