apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app
  labels:
    name: python-app
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: python-app
    spec:
      containers:
      - name: test
        image: cloudorbit.azurecr.io/python-app
        imagePullPolicy: Always
