apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-app
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: python-app
  targetCPUUtilizationPercentage: 80
