apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    name: spring-boot-app
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: acr.io/smartcity-256317/dev/ms/spring-boot-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"

---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-app
spec:
  selector:
    name: spring-boot-app
  ports:
  - name: port1
    protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-app
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: spring-boot-app
  targetCPUUtilizationPercentage: 80
